Danzor.Mvc/Controllers/DanfeController.cs
using Danzor.Print;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Danzor.Mvc.Controllers
{
    public class DanfeController : Controller
    {
        // GET: Danfe
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Danfe()
        {
            string path = HttpContext.Server.MapPath("~/Content/NFe28090708060730000190550020000001762000007303procNFe.xml");
            DanzorPrintViewer model = new DanzorPrintViewer(path);

            return View("~/Views/Danfe/Danfe.cshtml", model);
        }
    }
}

Danzor.Mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Danzor.Print;
using System.IO;

namespace Danzor.Mvc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Danzor.Mvc/Views/Danfe/Danfe.cshtml
@model Danzor.Print.DanzorPrintViewer

@{
   Layout = null;
}

<!DOCTYPE html>

<html>
<head>
   <meta name="viewport" content="width=device-width" />
   <title>DANFe</title>
   <link href="~/Content/css/danfe/danfe.min.css" rel="stylesheet" />
</head>
<body>
      <div class="danfe">
         @foreach (var page in Model.Pages)
         {
            <div class="page">
               @if (@page.IsFirstPage)
               {
                  @Html.Partial("~/Views/Danfe/_canhoto.cshtml", @page.Header)
               }

               @Html.Partial("~/Views/Danfe/_dados_nfe.cshtml", @page.Body)
               @Html.Partial("~/Views/Danfe/_destinatario.cshtml", @page.Body)

               @if (@page.IsFirstPage)
               {
                  @Html.Partial("~/Views/Danfe/_transportador.cshtml", @page.Body)
                  @Html.Partial("~/Views/Danfe/_imposto.cshtml", @page.Body)
                  @Html.Partial("~/Views/Danfe/_faturas.cshtml", @page.Body)
               }

               @Html.Partial("~/Views/Danfe/_dados_produtos.cshtml", @page.Body)

               @if (@page.IsLastPage)
               {
                  @Html.Partial("~/Views/Danfe/_dados_adicionais.cshtml", @page.Footer)
               }
            </div>
         }
      </div>
</body>

</html>

Danzor.Mvc/Views/Danfe/_canhoto.cshtml
@model Danzor.Print.DanzorHeader

<section class="bloco">
   <table id="canhoto">
      <tr>
         <td class="campo recebemos" colspan="2">
            <div class="conteudo fonte-5-pontos">RECEBEMOS @Model.emit.xNome.Value OS PRODUTOS CONSTANTES DA NOTA FISCAL INDICADA AO LADO</div>
         </td>
         <td class="campo numero-nfe" rowspan="2">
            <div class="conteudo centralizado negrito">NF-e</div>
            <div class="conteudo negrito">Nr: @Model.ide.cNF.Value</div>
            <div class="conteudo negrito">Série: @Model.ide.serie.Value</div>
         </td>
      </tr>
      <tr>
         <td class="campo data-recebimento">
            <div class="conteudo fonte-5-pontos">DATA DE RECEBIMENTO</div>
         </td>
         <td class="campo assinatura">
            <div class="conteudo fonte-5-pontos">IDENTIFICAÇÃO E ASSINATURA</div>
         </td>
      </tr>
   </table>
   <hr class="picote" />
</section>

Danzor.Mvc/Views/Danfe/_dados_adicionais.cshtml
@model Danzor.Print.DanzorFooter

<section class="bloco rodape">
   <table id="dados_adicionais">
      <tr>
         <td class="campo">
            <div class="conteudo negrito">DADOS ADICIONAIS</div>
         </td>
         <td class="campo">
            <div class="conteudo negrito">RESERVADO AO FISCO</div>
         </td>
      </tr>
      <tr>
         <td class="campo dados-adicionais">
            <div class="conteudo">
               @Model.infAdic.infCpl.Value
            </div>
         </td>
         <td class="campo reservado-fisco">
            <div class="conteudo">
               @Model.infAdic.infAdFisco.Value
            </div>
         </td>
      </tr>
   </table>
</section>

Danzor.Mvc/Views/Danfe/_dados_nfe.cshtml
@model Danzor.Print.DanzorBody

<section class="bloco">
   <table id="dados-nfe">
      <thead>
         <tr>
            <td rowspan="4" class="campo quadro-identificacao-emitente">
               <div class="conteudo negrito">
                  <h3>@Model.emit.xNome.Value</h3>
               </div>
               <div class="conteudo">
                  @Model.emit.enderEmit.xLgr.Value, @Model.emit.enderEmit.nro.Value <br />
                  @Model.emit.enderEmit.xBairro.Value <br />
                  @Model.emit.enderEmit.xMun.Value - @Model.emit.enderEmit.UF.Value <br />
                  @Model.emit.enderEmit.CEP.Value <br />
                  Tel: @Model.emit.enderEmit.fone.Value
               </div>
            </td>
            <td rowspan="4" class="campo quadro-descricao-danfe">
               <div class="conteudo negrito centralizado">
                  DANFE
               </div>
               <div class="conteudo negrito centralizado fonte-7-pontos">
                  DOCUMENTO AUXILIAR DA NOTA FISCAL ELETRÔNICA
               </div>
               <div class="conteudo">
                  <div class="conteudo duas-coluna fonte-5-pontos">
                     0 - ENTRADA <br />
                     1 - SAÍDA
                  </div>
                  <div class="conteudo duas-coluna centralizado negrito">
                     <span class="caixa">@Model.ide.tpEmis.Value</span>
                  </div>
               </div>
               <div class="conteudo negrito fonte-7-pontos">
                  Nr: @Model.ide.cNF.Value <br />
                  Série: @Model.ide.serie.Value <br />
                  Folha: @Model.page/@Model.size <br />
               </div>
            </td>
         </tr>
         <tr>
            <td class="campo quadro-codigo-de-barras-da-chave">
               <div class="conteudo centralizado"><h2>CODIGO DE BARRAS</h2></div>
            </td>
         </tr>
         <tr>
            <td class="campo codigo-de-barras-da-chave">
               <div class="conteudo negrito fonte-5-pontos">
                  CHAVE DE ACESSO DA NF-e
               </div>
               <div class="conteudo negrito">
                  @Model.protNFe.infProt.chNFe.Value
               </div>
               <div class="conteudo centralizado fonte-7-pontos">
                  Consulta de autenticidade no portal nacional da NF-e www.nfe.fazenda.gov.br/portal ou
                  no site da Sefaz autorizadora
               </div>
            </td>
         </tr>
         <tr>
            <td class="campo codigo-de-barras-da-chave">
               <div class="conteudo fonte-5-pontos">PROTOCOLO DE AUTORIZAÇÃO DE USO</div>
               <div class="conteudo">
                  @Model.protNFe.infProt.nProt.Value
                  @Model.protNFe.infProt.dhRecbto.ToDateTime().ToString()
               </div>
            </td>
         </tr>
      </thead>
   </table>

   <table class="sem-borda-superior">
      <thead>
         <tr>
            <td colspan="3" class="campo natureza-de-operacao">
               <div class="conteudo fonte-5-pontos">NATUREZA DA OPERAÇÃO</div>
               <div class="conteudo">@Model.ide.natOp.Value</div>
            </td>
         </tr>
         <tr>
            <td class="campo inscricao-estadual-emitente">
               <div class="conteudo fonte-5-pontos">INSCRIÇÃO ESTADUAL</div>
               <div class="conteudo">@Model.emit.IE.Value</div>
            </td>
            <td class="campo inscricao-estadual-st-emitente">
               <div class="conteudo fonte-5-pontos">INSCR.ESTADUAL SUBSTITUTO</div>
            </td>
            <td class="campo cnpj-emitente">
               <div class="conteudo fonte-5-pontos">CNPJ</div>
               <div class="conteudo">@Model.emit.CNPJ.Value</div>
            </td>
         </tr>
      </thead>
   </table>
</section>

Danzor.Mvc/Views/Danfe/_dados_produtos.cshtml
@model Danzor.Print.DanzorBody

<section class="bloco">
   <div class="conteudo negrito fonte-7-pontos">DADOS DOS PRODUTOS / SERVIÇOS</div>
   <table id="dados_produtos">
      <thead>
         <tr>
            <th class="campo">
               <div class="conteudo fonte-5-pontos">CÓDIGO</div>
            </th>
            <th class="campo">
               <div class="conteudo fonte-5-pontos">DESCRIÇÃO DOS PRODUTOS / SERVIÇOS</div>
            </th>
            <th class="campo">
               <div class="conteudo fonte-5-pontos">NCM/SH</div>
            </th>
            <th class="campo">
               <div class="conteudo fonte-5-pontos">CST</div>
            </th>
            <th class="campo">
               <div class="conteudo fonte-5-pontos">CFOP</div>
            </th>
            <th class="campo">
               <div class="conteudo fonte-5-pontos">UNID</div>
            </th>
            <th class="campo">
               <div class="conteudo fonte-5-pontos">QUANT</div>
            </th>
            <th class="campo">
               <div class="conteudo fonte-5-pontos">VLR.UNIT.</div>
            </th>
            <th class="campo">
               <div class="conteudo fonte-5-pontos">VLR.TOTAL</div>
            </th>
            <th class="campo">
               <div class="conteudo fonte-5-pontos">BC.ICMS</div>
            </th>
            <th class="campo">
               <div class="conteudo fonte-5-pontos">VL.ICMS</div>
            </th>
            <th class="campo">
               <div class="conteudo fonte-5-pontos">VLR I.P.I</div>
            </th>
            <th class="campo">
               <div class="conteudo fonte-5-pontos">
                  Aliq
                  ICMS
               </div>
            </th>
            <th class="campo">
               <div class="conteudo fonte-5-pontos">
                  Aliq
                  IPI
               </div>
            </th>
         </tr>
      </thead>

      @foreach (var item in Model.det)
      {
         <tr>
            <td class="campo sem-borda-superior-inferior">
               <div class="conteudo fonte-7-pontos">
                  @item.prod.cProd.Value
               </div>
            </td>
            <td class="campo sem-borda-superior-inferior">
               <div class="conteudo fonte-7-pontos">
                  @item.prod.xProd.Value
               </div>
            </td>
            <td class="campo sem-borda-superior-inferior">
               <div class="conteudo fonte-7-pontos">
                  @item.prod.NCM.Value
               </div>
            </td>
            <td class="campo sem-borda-superior-inferior">
               <div class="conteudo fonte-7-pontos">
                  @item.imposto.ICMS.First().CST.Value
               </div>
            </td>
            <td class="campo sem-borda-superior-inferior">
               <div class="conteudo fonte-7-pontos">
                  @item.prod.CFOP.Value
               </div>
            </td>
            <td class="campo sem-borda-superior-inferior">
               <div class="conteudo fonte-7-pontos">
                  @item.prod.uCom.Value
               </div>
            </td>
            <td class="campo sem-borda-superior-inferior">
               <div class="conteudo fonte-7-pontos">
                  @item.prod.qCom.Value
               </div>
            </td>
            <td class="campo sem-borda-superior-inferior">
               <div class="conteudo fonte-7-pontos">
                  @item.prod.vUnCom.Value
               </div>
            </td>
            <td class="campo sem-borda-superior-inferior">
               <div class="conteudo fonte-7-pontos">
                  @item.prod.vProd.Value
               </div>
            </td>
            <td class="campo sem-borda-superior-inferior">
               <div class="conteudo fonte-7-pontos">
                  @item.prod.vUnTrib.Value
               </div>
            </td>
            <td class="campo sem-borda-superior-inferior">
               <div class="conteudo fonte-7-pontos">
                  @item.imposto.ICMS.First().vICMS.Value
               </div>
            </td>
            <td class="campo sem-borda-superior-inferior">
               <div class="conteudo fonte-7-pontos">
                  @if (item.imposto.IPI.IPITrib.vIPI.Value == string.Empty)
                  {
                     @item.imposto.IPI.IPITrib.vIPI.Value
                  }
                  else
                  {
                     <span>0</span>
                  }
               </div>
            </td>
            <td class="campo sem-borda-superior-inferior">
               <div class="conteudo fonte-7-pontos">
                  @item.imposto.ICMS.First().pICMS.Value
               </div>
            </td>
            <td class="campo sem-borda-superior-inferior">
               <div class="conteudo fonte-7-pontos">
                  @if (item.imposto.IPI.IPITrib.pIPI.Value == string.Empty)
                  {
                     @item.imposto.IPI.IPITrib.pIPI.Value
                  }
                  else
                  {
                     <span>0</span>
                  }
               </div>
            </td>
         </tr>

      }
   </table>

</section>

Danzor.Mvc/Views/Danfe/_destinatario.cshtml
@model Danzor.Print.DanzorBody

<section class="bloco">
   <div class="conteudo negrito fonte-7-pontos">DESTINATÁRIO/REMETENTE</div>
   <table>
      <tr>
         <td colspan="3" class="campo razao-social">
            <div class="conteudo fonte-5-pontos">NOME / RAZÃO SOCIAL</div>
            <div class="conteudo">
               @Model.dest.xNome.Value
            </div>
         </td>
         <td class="campo cnpj-destinatario">
            <div class="conteudo fonte-5-pontos">CNPJ / CPF</div>
            <div class="conteudo">
               @Model.dest.CNPJ.Value
            </div>
         </td>
         <td class="campo data-emissao">
            <div class="conteudo fonte-5-pontos">DATA DE EMISSÃO</div>
            <div class="conteudo">
               @Model.ide.dEmi.ToDateTime().ToString("dd/MM/yyyy")
            </div>
         </td>
      </tr>
      <tr>
         <td colspan="2" class="campo endereco-destinatario">
            <div class="conteudo fonte-5-pontos">ENDEREÇO</div>
            <div class="conteudo">
               @Model.dest.enderDest.xLgr.Value &nbsp;
               @Model.dest.enderDest.nro.Value
            </div>
         </td>
         <td class="campo bairro-destinatario">
            <div class="conteudo fonte-5-pontos">BAIRRO / DISTRITO</div>
            <div class="conteudo">
               @Model.dest.enderDest.xBairro.Value
            </div>
         </td>
         <td class="campo cep-destinatario">
            <div class="conteudo fonte-5-pontos">CEP</div>
            <div class="conteudo">
               @Model.dest.enderDest.CEP.Value
            </div>
         </td>
         <td class="campo data-entrada-destinatario">
            <div class="conteudo fonte-5-pontos">DATA ENTRADA / SAÍDA</div>
            <div class="conteudo">
               @Model.ide.dEmi.ToDateTime().ToString("dd/MM/yyyy")
            </div>
         </td>
      </tr>
      <tr>
         <td class="campo municipio-destinatario">
            <div class="conteudo fonte-5-pontos">MUNICÍPIO</div>
            <div class="conteudo">
               @Model.dest.enderDest.xMun.Value
            </div>
         </td>
         <td class="campo fone-fax-destinatario">
            <div class="conteudo fonte-5-pontos">TELEFONE</div>
            <div class="conteudo">
               @Model.dest.enderDest.fone.Value
            </div>
         </td>
         <td class="campo uf-destinatario">
            <div class="conteudo fonte-5-pontos">UF</div>
            <div class="conteudo">
               @Model.dest.enderDest.UF.Value
            </div>
         </td>
         <td class="campo inscricao-destinatario">
            <div class="conteudo fonte-5-pontos">INSCRIÇÃO ESTADUAL</div>
            <div class="conteudo">
               @Model.dest.IE.Value
            </div>
         </td>
         <td class="campo hora-entrada-saida">
            <div class="conteudo fonte-5-pontos">HORA ENTRADA / SAÍDA</div>
            <div class="conteudo">
               @Model.ide.dEmi.ToDateTime().ToString("hh:mm")
            </div>
         </td>
      </tr>
   </table>
</section>

Danzor.Mvc/Views/Danfe/_faturas.cshtml
@model Danzor.Print.DanzorBody

<section class="bloco">
   <div class="conteudo negrito fonte-7-pontos">FATURAS</div>
   <table class="sem-bordas-laterais">
      <tr>
         <td>
            <table class="sem-bordas">
               <tr>
                  @foreach (var duplicata in @Model.cobr.dup)
                  {
                     <td class="campo sem-bordas">
                        <div class="conteudo tres-colunas">
                           <div class="conteudo fonte-5-pontos">NÚMERO</div>
                           <div class="conteudo fonte-7-pontos">@duplicata.nDup.Value</div>
                        </div>
                        <div class="conteudo tres-colunas">
                           <div class="conteudo fonte-5-pontos">NÚMERO</div>
                           <div class="conteudo fonte-7-pontos">@duplicata.dVenc.Value</div>
                        </div>
                        <div class="conteudo tres-colunas">
                           <div class="conteudo fonte-5-pontos">NÚMERO</div>
                           <div class="conteudo fonte-7-pontos">@duplicata.vDup.Value</div>
                        </div>
                     </td>
                  }
               </tr>
            </table>
         </td>
      </tr>
   </table>
</section>

Danzor.Mvc/Views/Danfe/_imposto.cshtml
@model Danzor.Print.DanzorBody

<section class="bloco">
   <div class="conteudo negrito fonte-7-pontos">CÁLCULO DO IMPOSTO</div>
   <table>
      <tr>
         <td class="campo base-calculo-icms">
            <div class="conteudo fonte-5-pontos">BASE DE CÁLCULO ICMS</div>
            <div class="conteudo">
               @Model.total.ICMSTot.vBC.Value
            </div>
         </td>
         <td class="campo valor-do-icms">
            <div class="conteudo fonte-5-pontos">VALOR DO ICMS</div>
            <div class="conteudo">
               @Model.total.ICMSTot.vICMS.Value
            </div>
         </td>
         <td class="campo base-de-cálculo-do-icms-st">
            <div class="conteudo fonte-5-pontos">BASE DE CÁLCULO ICMS ST</div>
            <div class="conteudo">
               @Model.total.ICMSTot.vBCST.Value
            </div>
         </td>
         <td class="campo valor-do-icms-st">
            <div class="conteudo fonte-5-pontos">VALOR DO ICMS ST</div>
            <div class="conteudo">
               @Model.total.ICMSTot.vST.Value
            </div>
         </td>
         <td class="campo valor-total-dos-produtos">
            <div class="conteudo fonte-5-pontos">VALOR TOTAL DOS PRODUTOS</div>
            <div class="conteudo">
               @Model.total.ICMSTot.vProd.Value
            </div>
         </td>
      </tr>
   </table>

   <table class="sem-borda-superior">
      <tr>
         <td class="campo valor-do-frete">
            <div class="conteudo fonte-5-pontos">VALOR DO FRETE</div>
            <div class="conteudo">
               @Model.total.ICMSTot.vFrete.Value
            </div>
         </td>
         <td class="campo valor-do-seguro">
            <div class="conteudo fonte-5-pontos">VALOR DO SEGURO</div>
            <div class="conteudo">
               @Model.total.ICMSTot.vSeg.Value
            </div>
         </td>
         <td class="campo desconto">
            <div class="conteudo fonte-5-pontos">DESCONTO</div>
            <div class="conteudo">
               @Model.total.ICMSTot.vDesc.Value
            </div>
         </td>
         <td class="campo outras-despesas-acessórias">
            <div class="conteudo fonte-5-pontos">OUTRAS DESPESAS ACESSÓRIAS</div>
            <div class="conteudo">
               @Model.total.ICMSTot.vOutro.Value
            </div>
         </td>
         <td class="campo valor-do-ipi">
            <div class="conteudo fonte-5-pontos">VALOR DO IPI</div>
            <div class="conteudo">
               @Model.total.ICMSTot.vIPI.Value
            </div>
         </td>
         <td class="campo valor-total-da-nota">
            <div class="conteudo fonte-5-pontos">VALOR TOTAL DA NOTA</div>
            <div class="conteudo">
               @Model.total.ICMSTot.vNF.Value
            </div>
         </td>
      </tr>
   </table>
</section>

Danzor.Mvc/Views/Danfe/_transportador.cshtml
@model Danzor.Print.DanzorBody

<section class="bloco">
   <div class="conteudo negrito fonte-7-pontos">TRANSPORTADOR / VOLUMES TRANSPORTADOS</div>
   <table>
      <tr>
         <td class="campo razao-social-transportador">
            <div class="conteudo fonte-5-pontos">NOME / RAZÃO SOCIAL</div>
            <div class="conteudo">
            </div>
         </td>
         <td class="campo frete-por-conta-transportador">
            <div class="conteudo fonte-5-pontos">FRETE POR CONTA</div>
            <div class="conteudo duas-coluna fonte-5-pontos">
               0 - EMITENTE <br />
               1 - DESTINAT.
            </div>
            <div class="conteudo duas-coluna centralizado negrito">
               <span class="caixa">
                  @Model.transp.modFrete.Value
               </span>
            </div>
         </td>
         <td class="campo codigo-antt-transportador">
            <div class="conteudo fonte-5-pontos">CÓDIGO ANTT</div>
            <div class="conteudo">

            </div>
         </td>
         <td class="campo placa-veiculo-transportador">
            <div class="conteudo fonte-5-pontos">PLACA DO VEÍCULO</div>
         </td>
         <td class="campo uf-placa-transportador">
            <div class="conteudo fonte-5-pontos">UF</div>
         </td>
         <td class="campo cnpj-transportador">
            <div class="conteudo fonte-5-pontos">CNPJ / CPF</div>
         </td>
      </tr>
      <tr>
         <td class="campo endereco-transportador">
            <div class="conteudo fonte-5-pontos">ENDEREÇO</div>

         </td>
         <td colspan="3" class="campo municipio-transportador">
            <div class="conteudo fonte-5-pontos">MUNICÍPIO</div>

         </td>
         <td class="campo uf-transportador">
            <div class="conteudo fonte-5-pontos">UF</div>

         </td>
         <td class="campo inscricao-transportador">
            <div class="conteudo fonte-5-pontos">INSCRIÇÃO ESTADUAL</div>

         </td>
      </tr>
   </table>
   <table class="sem-borda-superior">
      <tr>
         <td class="campo quantidade-transportador">
            <div class="conteudo fonte-5-pontos">QUANTIDADE</div>
            <div class="conteudo">

            </div>
         </td>
         <td class="campo especie-transportador">
            <div class="conteudo fonte-5-pontos">ESPÉCIE</div>
            <div class="conteudo">
               @Model.transp.vol.esp.Value
            </div>
         </td>
         <td class="campo marca-transportador">
            <div class="conteudo fonte-5-pontos">MARCA</div>
            <div class="conteudo">
               @Model.transp.vol.marca.Value
            </div>
         </td>
         <td class="campo numero-transportador">
            <div class="conteudo fonte-5-pontos">NÚMERO</div>
            <div class="conteudo">

            </div>
         </td>
         <td class="campo peso-bruto-transportador">
            <div class="conteudo fonte-5-pontos">PESO BRUTO</div>
            <div class="conteudo">
               @Model.transp.vol.pesoB.Value
            </div>
         </td>
         <td class="campo peso-liquido-transportador">
            <div class="conteudo fonte-5-pontos">PESO LÍQUIDO</div>
            <div class="conteudo">
               @Model.transp.vol.pesoL.Value
            </div>
         </td>
      </tr>
   </table>
</section>

Danzor.Mvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
   @Html.ActionLink("EMITIR DANFE", "Danfe", "Danfe")
</div>